name: Android

on:
  push:
    tags:
      - "v*.*.*"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
      - run: flutter pub get
      - run: flutter build apk --dart-define=VERSION=${GITHUB_REF#refs/tags/v}

      -
        name: Step 3 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with:
          name: lazypig-android.apk
          path: build/app/outputs/flutter-apk/app-release.apk