name: IOS

on:
  push:
    tags:
      - "v*.*.*"

jobs:

  build:
    runs-on: macos-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          architecture: x64
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign --dart-define=VERSION=${GITHUB_REF#refs/tags/v}

      -
      name: Step 3 - Use the Upload Artifact GitHub Action
      uses: actions/upload-artifact@v2
      with:
        name: lazypig-ios.app
        path: /Users/runner/work/lazypig-app/lazypig-app/build/ios/iphoneos/Runner.app