name: IOS

on:
  push:
    tags:
      - "v*.*.*"

jobs:

  build:
    runs-on: macos-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          architecture: x64
      - run: flutter pub get
      - run: flutter build ipa --release --dart-define=VERSION=${GITHUB_REF#refs/tags/v}
      - run: mv build/ios/ipa lazypig-ios
      - run: tar cfv lazypig-ios.tar lazypig-ios
      -
        name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            lazypig-ios.tar