name: Linux

on:
  push:
    tags:
      - "v*.*.*"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter config --enable-linux-desktop
      - run: flutter pub get
      - run: flutter build linux --dart-define=VERSION=${GITHUB_REF#refs/tags/v}
      - run: mv build/linux/x64/release/bundle lazypig-linux

      -
        name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            lazypig-linux