name: MacOS

on:
  push:
    tags:
      - "v*.*.*"

jobs:

  build:
    runs-on: macos-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
      - run: flutter config --enable-macos-desktop
      - run: flutter pub get
      - run: flutter build macos --dart-define=VERSION=${GITHUB_REF#refs/tags/v}
      - run: mv build/macos/Build/Products/Release/lazy_pig.app lazypig-macos.app

      -
        name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            lazypig-macos.app