name: Windows

on:
  push:
    tags:
      - "v*.*.*"

jobs:

  build:
    runs-on: windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
      - run: flutter config --enable-windows-desktop
      - run: flutter pub get
      - run: flutter build windows --dart-define=VERSION=${GITHUB_REF#refs/tags/v}

      -
        name: Step 3 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: build\windows\runner\Release