name: Windows

on:
  push:
    tags:
      - "v*.*.*"

jobs:

  build:
    runs-on: windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
      - run: flutter config --enable-windows-desktop
      - run: flutter pub get
      - run: flutter build windows --dart-define=VERSION=${GITHUB_REF#refs/tags/v}
      - run: flutter pub run msix:create
      - run: move build\windows\runner\Release lazypig-windows

      -
        name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            lazypig-windows